name: CD - Deploy para Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Atualizado para Node.js 18

      - name: Instalar dependências
        run: npm install

      - name: Fazer deploy na Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.GITHUBACTIONSTESTVERCEL }}
        run: npx vercel --prod --token $VERCEL_TOKEN
