name: CD - Deploy para Vercel

on:
  push:
    branches:
      - main # Realiza o deploy em cada push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependências
        run: npm install

      - name: Rodar build (caso necessário para o frontend)
        run: npm run build

      - name: Fazer deploy na Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.GITHUBACTIONSTESTVERCEL }} # Use o nome exato do seu secret
        run: npx vercel --prod --token $VERCEL_TOKEN
